// Product data store

export interface Product {
  id: string
  name: string
  brand: string
  category: string
  price: number
  rating: number
  image: string
  images?: string[]
  isNew?: boolean
  releaseDate: string
  description?: string
  fullDescription?: string
  details?: string[]
  care?: string[]
  sizes?: string[]
  reviews?: number
}

export const products: Product[] = [
  {
    id: "1",
    name: "Air Max Pulse",
    brand: "Nike",
    category: "Running",
    price: 149.99,
    rating: 4.8,
    image: "/images/nike-air-max-pulse.png",
    images: [
      "/images/nike-air-max-pulse.png",
      "/images/nike-air-max-pulse-2.png",
      "/images/nike-air-max-pulse-3.png",
      "/images/nike-air-max-pulse-4.png",
    ],
    isNew: true,
    releaseDate: "2023-05-15",
    description: "Elevate your run with responsive cushioning and sleek design.",
    fullDescription:
      "The Nike Air Max Pulse brings a bold new look to the Air Max family. Inspired by the energy of London's music scene, this sneaker features a textile and synthetic upper with a unique molded design. The visible Air-Sole unit in the heel provides responsive cushioning, while the rubber outsole offers durable traction on various surfaces. The padded, low-cut collar looks sleek and feels comfortable.",
    details: [
      "Textile and synthetic upper for durability",
      "Visible Air-Sole unit in the heel",
      "Rubber outsole for traction and durability",
      "Padded, low-cut collar for comfort",
      "Pull tab on heel for easy on and off",
      "Color Shown: Black/White/Anthracite",
    ],
    care: [
      "Spot clean with mild detergent and water",
      "Air dry away from direct heat",
      "Use a soft brush to remove dirt from outsole",
      "Store in a cool, dry place",
      "Avoid prolonged exposure to direct sunlight",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11"],
    reviews: 124,
  },
  {
    id: "2",
    name: "Ultra Boost 23",
    brand: "Adidas",
    category: "Running",
    price: 189.99,
    rating: 4.7,
    image: "/images/adidas-ultra-boost.png",
    images: [
      "/images/adidas-ultra-boost.png",
      "/images/adidas-ultra-boost.png",
      "/images/adidas-ultra-boost.png",
      "/images/adidas-ultra-boost.png",
    ],
    isNew: false,
    releaseDate: "2023-01-10",
    description: "Responsive cushioning for maximum energy return on every run.",
    fullDescription:
      "The Adidas Ultra Boost 23 represents the pinnacle of running technology. Featuring a Primeknit+ upper that adapts to your foot's movement and provides a supportive fit. The full-length Boost midsole delivers incredible energy return with every step, while the Continental™ Rubber outsole provides exceptional grip in all conditions. The Linear Energy Push system enhances stability for a smooth stride.",
    details: [
      "Primeknit+ upper for adaptive fit",
      "Boost midsole for responsive cushioning",
      "Continental™ Rubber outsole for superior traction",
      "Linear Energy Push system for stability",
      "Heel counter for secure fit",
      "Color Shown: Core Black/Cloud White",
    ],
    care: [
      "Machine wash cold with like colors",
      "Remove insole before washing",
      "Air dry away from direct heat",
      "Do not bleach or dry clean",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 98,
  },
  {
    id: "3",
    name: "RS-X Reinvention",
    brand: "Puma",
    category: "Lifestyle",
    price: 129.99,
    rating: 4.5,
    image: "/images/puma-rs-x.png",
    images: ["/images/puma-rs-x.png", "/images/puma-rs-x.png", "/images/puma-rs-x.png", "/images/puma-rs-x.png"],
    isNew: true,
    releaseDate: "2023-06-20",
    description: "Chunky silhouette with bold colorways for street-ready style.",
    fullDescription:
      "The PUMA RS-X Reinvention reimagines PUMA's Running System technology from the 1980s with exaggerated design elements and bold material mixes. The chunky silhouette features a mesh and textile upper with leather and suede overlays for a layered look. The RS cushioning technology in the midsole provides comfort, while the rubber outsole ensures grip and durability.",
    details: [
      "Mesh and textile upper with suede and leather overlays",
      "RS cushioning technology in midsole",
      "Rubber outsole for grip and durability",
      "Padded collar and tongue for comfort",
      "PUMA branding details throughout",
      "Color Shown: Puma White/Red Blast",
    ],
    care: [
      "Wipe clean with a damp cloth",
      "Use a soft brush for suede sections",
      "Air dry at room temperature",
      "Use specialized sneaker cleaner for tough stains",
      "Store away from direct sunlight",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 76,
  },
  {
    id: "4",
    name: "Classic Leather",
    brand: "Reebok",
    category: "Lifestyle",
    price: 99.99,
    rating: 4.6,
    image: "/images/reebok-classic.png",
    images: [
      "/images/reebok-classic.png",
      "/images/reebok-classic.png",
      "/images/reebok-classic.png",
      "/images/reebok-classic.png",
    ],
    isNew: false,
    releaseDate: "2022-11-05",
    description: "Timeless design with premium leather for everyday style.",
    fullDescription:
      "The Reebok Classic Leather is a timeless silhouette that has remained relevant since its debut in 1983. Featuring a premium leather upper that provides durability and a heritage look. The EVA midsole offers lightweight cushioning, while the rubber outsole delivers traction and durability. The low-cut design allows for freedom of movement and versatile styling options.",
    details: [
      "Premium leather upper for comfort and support",
      "EVA midsole for lightweight cushioning",
      "High-abrasion rubber outsole",
      "Removable sockliner accommodates orthotics",
      "Low-cut design for mobility",
      "Color Shown: White/Gum",
    ],
    care: [
      "Wipe clean with a damp cloth",
      "Use leather conditioner to maintain suppleness",
      "Allow to air dry naturally",
      "Use white shoe polish for touch-ups if needed",
      "Store with shoe trees to maintain shape",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 112,
  },
  {
    id: "5",
    name: "Jordan 4 Retro",
    brand: "Nike",
    category: "Basketball",
    price: 219.99,
    rating: 4.9,
    image: "/images/jordan-4-retro.png",
    images: [
      "/images/jordan-4-retro.png",
      "/images/jordan-4-retro.png",
      "/images/jordan-4-retro.png",
      "/images/jordan-4-retro.png",
    ],
    isNew: false,
    releaseDate: "2022-08-15",
    description: "Iconic silhouette with premium materials and visible Air cushioning.",
    fullDescription:
      "The Air Jordan 4 Retro brings back the legendary silhouette that Michael Jordan wore when he hit 'The Shot' in the 1989 playoffs. Featuring a premium leather and synthetic upper with the iconic mesh panels and supportive 'wings'. The visible Air-Sole unit in the heel provides responsive cushioning, while the rubber outsole with herringbone pattern offers excellent traction on and off the court.",
    details: [
      "Premium leather and synthetic upper",
      "Mesh panels for breathability",
      "Visible Air-Sole unit in heel",
      "Rubber outsole with herringbone pattern",
      "Padded collar and tongue for comfort",
      "Color Shown: White/Fire Red/Black/Tech Grey",
    ],
    care: [
      "Clean with mild soap and water",
      "Use a soft brush for nubuck or suede sections",
      "Air dry away from direct heat",
      "Use specialized sneaker protector spray",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 156,
  },
  {
    id: "6",
    name: "Yeezy Boost 350",
    brand: "Adidas",
    category: "Lifestyle",
    price: 229.99,
    rating: 4.8,
    image: "/images/yeezy-boost-350.png",
    images: [
      "/images/yeezy-boost-350.png",
      "/images/yeezy-boost-350.png",
      "/images/yeezy-boost-350.png",
      "/images/yeezy-boost-350.png",
    ],
    isNew: false,
    releaseDate: "2022-09-22",
    description: "Revolutionary design with Primeknit upper and responsive Boost cushioning.",
    fullDescription:
      "The Adidas Yeezy Boost 350 is a revolutionary silhouette designed by Kanye West. The shoe features a Primeknit upper that wraps the foot in adaptive support and ultralight comfort. The full-length Boost midsole provides responsive cushioning, while the rubber outsole offers durable traction. The distinctive center stitching and pull tab add signature style elements to this coveted design.",
    details: [
      "Primeknit upper for adaptive fit",
      "Full-length Boost midsole for responsive cushioning",
      "Rubber outsole for durable traction",
      "Distinctive center stitching detail",
      "Heel pull tab for easy on and off",
      "Color Shown: Beluga 2.0",
    ],
    care: [
      "Spot clean with mild detergent and water",
      "Use soft brush for Primeknit upper",
      "Air dry at room temperature",
      "Use specialized sneaker cleaner for tough stains",
      "Store away from direct sunlight",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12", "US 13"],
    reviews: 203,
  },
  {
    id: "7",
    name: "Suede Classic",
    brand: "Puma",
    category: "Lifestyle",
    price: 79.99,
    rating: 4.4,
    image: "/images/puma-suede.png",
    images: ["/images/puma-suede.png", "/images/puma-suede.png", "/images/puma-suede.png", "/images/puma-suede.png"],
    isNew: false,
    releaseDate: "2022-07-10",
    description: "Iconic suede upper with classic formstrip for timeless street style.",
    fullDescription:
      "The PUMA Suede Classic is a true icon that has been a staple in street culture since its introduction in 1968. Featuring a premium suede upper with the signature formstrip and a rubber outsole for grip and durability. The padded collar and tongue provide comfort, while the lace closure ensures a secure fit. This timeless silhouette has transcended generations and continues to be a must-have in any sneaker collection.",
    details: [
      "Premium suede upper for comfort and style",
      "Signature PUMA formstrip at lateral and medial sides",
      "Rubber outsole for grip and durability",
      "Padded collar and tongue for comfort",
      "Lace closure for secure fit",
      "Color Shown: Peacoat/White",
    ],
    care: [
      "Use a suede brush to remove dirt and restore nap",
      "Apply suede protector spray before first wear",
      "Clean with specialized suede cleaner",
      "Allow to air dry naturally",
      "Use shoe trees to maintain shape",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 89,
  },
  {
    id: "8",
    name: "Chuck Taylor All Star",
    brand: "Converse",
    category: "Lifestyle",
    price: 59.99,
    rating: 4.5,
    image: "/images/converse-chuck-taylor.png",
    images: [
      "/images/converse-chuck-taylor.png",
      "/images/converse-chuck-taylor.png",
      "/images/converse-chuck-taylor.png",
      "/images/converse-chuck-taylor.png",
    ],
    isNew: false,
    releaseDate: "2022-05-18",
    description: "Timeless canvas high-top with iconic ankle patch and rubber toe cap.",
    fullDescription:
      "The Converse Chuck Taylor All Star is perhaps the most iconic sneaker of all time, virtually unchanged since its debut in 1917. Featuring a durable canvas upper with the signature rubber toe cap and ankle patch. The medial eyelets enhance breathability, while the rubber outsole provides traction and durability. This versatile silhouette has been embraced by athletes, musicians, artists, and fashion enthusiasts for over a century.",
    details: [
      "Durable canvas upper",
      "Signature rubber toe cap and ankle patch",
      "Medial eyelets for breathability",
      "Rubber outsole for traction and durability",
      "Lace-up closure for adjustable fit",
      "Color Shown: Optical White",
    ],
    care: [
      "Machine wash cold with mild detergent",
      "Air dry away from direct heat",
      "Use magic eraser for rubber toe cap and midsole",
      "Apply canvas protector spray",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 178,
  },
  {
    id: "9",
    name: "Dunk Low",
    brand: "Nike",
    category: "Skateboarding",
    price: 109.99,
    rating: 4.7,
    image: "/images/nike-dunk-low.png",
    images: [
      "/images/nike-dunk-low.png",
      "/images/nike-dunk-low.png",
      "/images/nike-dunk-low.png",
      "/images/nike-dunk-low.png",
    ],
    isNew: true,
    releaseDate: "2023-04-12",
    description: "Iconic basketball-turned-skate silhouette with clean colorblocking.",
    fullDescription:
      "The Nike Dunk Low was created for the hardwood but taken to the streets. This iconic silhouette features a leather upper with perforations in the toe box for breathability. The padded, low-cut collar provides a comfortable fit, while the rubber outsole with pivot point offers excellent traction. Originally designed for basketball in the 1980s, the Dunk was adopted by skaters in the 2000s and has since become a streetwear staple.",
    details: [
      "Leather upper for durability and support",
      "Perforations in toe box for breathability",
      "Padded, low-cut collar for comfort",
      "Rubber outsole with pivot point for traction",
      "Foam midsole for lightweight cushioning",
      "Color Shown: Black/White",
    ],
    care: [
      "Wipe clean with a damp cloth",
      "Use leather conditioner to maintain suppleness",
      "Clean white midsoles with mild soap and water",
      "Allow to air dry naturally",
      "Use shoe trees to maintain shape",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 134,
  },
  {
    id: "10",
    name: "NMD R1",
    brand: "Adidas",
    category: "Lifestyle",
    price: 149.99,
    rating: 4.6,
    image: "/images/adidas-nmd-r1.png",
    images: [
      "/images/adidas-nmd-r1.png",
      "/images/adidas-nmd-r1.png",
      "/images/adidas-nmd-r1.png",
      "/images/adidas-nmd-r1.png",
    ],
    isNew: false,
    releaseDate: "2022-10-30",
    description: "Modern silhouette with Boost cushioning and distinctive midsole plugs.",
    fullDescription:
      "The Adidas NMD R1 is a modern silhouette inspired by iconic Adidas running models from the 1980s. Featuring a Primeknit or mesh upper for a sock-like fit and breathability. The full-length Boost midsole provides responsive cushioning, while the distinctive EVA plugs add stability and style. The rubber outsole offers durable traction, making this a perfect blend of heritage inspiration and modern technology.",
    details: [
      "Primeknit or mesh upper for sock-like fit",
      "Full-length Boost midsole for responsive cushioning",
      "Distinctive EVA plugs for stability and style",
      "Rubber outsole for durable traction",
      "Pull tab on heel for easy on and off",
      "Color Shown: Core Black/Carbon",
    ],
    care: [
      "Spot clean with mild detergent and water",
      "Use soft brush for Primeknit or mesh upper",
      "Air dry at room temperature",
      "Use specialized sneaker cleaner for tough stains",
      "Store away from direct sunlight",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 108,
  },
  {
    id: "11",
    name: "Old Skool",
    brand: "Vans",
    category: "Skateboarding",
    price: 69.99,
    rating: 4.5,
    image: "/images/vans-old-skool.png",
    images: [
      "/images/vans-old-skool.png",
      "/images/vans-old-skool.png",
      "/images/vans-old-skool.png",
      "/images/vans-old-skool.png",
    ],
    isNew: false,
    releaseDate: "2022-06-25",
    description: "Skate icon with signature side stripe and vulcanized construction.",
    fullDescription:
      "The Vans Old Skool is a skate icon that has transcended its original purpose to become a global fashion staple. Featuring a durable suede and canvas upper with the signature side stripe. The padded collar provides support and flexibility, while the vulcanized construction offers board feel and control. The waffle outsole delivers grip and durability, making this a favorite among skaters and fashion enthusiasts alike.",
    details: [
      "Suede and canvas upper for durability",
      "Signature side stripe",
      "Padded collar for support and flexibility",
      "Vulcanized construction for board feel",
      "Waffle outsole for grip and durability",
      "Color Shown: Black/White",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Use soft brush for suede sections",
      "Air dry away from direct heat",
      "Apply suede protector spray",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12"],
    reviews: 145,
  },
  {
    id: "12",
    name: "574 Core",
    brand: "New Balance",
    category: "Lifestyle",
    price: 89.99,
    rating: 4.4,
    image: "/images/new-balance-574.png",
    images: [
      "/images/new-balance-574.png",
      "/images/new-balance-574.png",
      "/images/new-balance-574.png",
      "/images/new-balance-574.png",
    ],
    isNew: false,
    releaseDate: "2022-08-05",
    description: "Heritage-inspired design with ENCAP midsole technology for all-day comfort.",
    fullDescription:
      "The New Balance 574 Core is a heritage-inspired silhouette that combines classic design with modern comfort. Featuring a suede and mesh upper for durability and breathability. The ENCAP midsole technology combines a durable polyurethane rim with soft EVA core for all-day comfort and support. The carbon rubber outsole provides durability in high-wear areas, making this a versatile option for everyday wear.",
    details: [
      "Suede and mesh upper for durability and breathability",
      "ENCAP midsole technology for comfort and support",
      "Carbon rubber outsole for durability",
      "Padded collar and tongue for comfort",
      "Lace closure for secure fit",
      "Color Shown: Grey/Navy",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Use soft brush for suede sections",
      "Air dry away from direct heat",
      "Apply suede protector spray",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12", "US 13"],
    reviews: 92,
  },
  {
    id: "13",
    name: "ZoomX Vaporfly Next%",
    brand: "Nike",
    category: "Running",
    price: 249.99,
    rating: 4.9,
    image: "/images/nike-zoomx-vaporfly.png",
    images: [
      "/images/nike-zoomx-vaporfly.png",
      "/images/nike-zoomx-vaporfly.png",
      "/images/nike-zoomx-vaporfly.png",
      "/images/nike-zoomx-vaporfly.png",
    ],
    isNew: true,
    releaseDate: "2023-03-10",
    description: "Elite racing shoe with carbon fiber plate and ZoomX foam for maximum speed.",
    fullDescription:
      "The Nike ZoomX Vaporfly Next% is designed for elite runners seeking maximum speed. Featuring a lightweight VaporWeave upper that's highly breathable and absorbs less water than traditional materials. The full-length carbon fiber plate works with the ZoomX foam to deliver exceptional energy return and propulsion. The offset heel design reduces Achilles strain, while the contoured forefoot provides a more natural toe-off.",
    details: [
      "VaporWeave upper for lightweight breathability",
      "Full-length carbon fiber plate for propulsion",
      "ZoomX foam for exceptional energy return",
      "Offset heel design reduces Achilles strain",
      "Contoured forefoot for natural toe-off",
      "Color Shown: Hyper Turquoise/Black",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Remove insole to dry separately",
      "Avoid machine washing",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 87,
  },
  {
    id: "14",
    name: "Ultraboost 22",
    brand: "Adidas",
    category: "Running",
    price: 199.99,
    rating: 4.7,
    image: "/images/adidas-ultraboost-22.png",
    images: [
      "/images/adidas-ultraboost-22.png",
      "/images/adidas-ultraboost-22.png",
      "/images/adidas-ultraboost-22.png",
      "/images/adidas-ultraboost-22.png",
    ],
    isNew: false,
    releaseDate: "2022-12-15",
    description: "Responsive running shoe with Primeknit+ upper and full-length Boost cushioning.",
    fullDescription:
      "The Adidas Ultraboost 22 is engineered for responsive running with a focus on women's-specific fit. Featuring a Primeknit+ upper that adapts to your foot's movement and provides a supportive fit. The full-length Boost midsole delivers incredible energy return with every step, while the Continental™ Rubber outsole provides exceptional grip in all conditions. The Linear Energy Push system enhances stability for a smooth stride.",
    details: [
      "Primeknit+ upper for adaptive fit",
      "Full-length Boost midsole for responsive cushioning",
      "Continental™ Rubber outsole for exceptional grip",
      "Linear Energy Push system for stability",
      "Women's-specific fit based on foot scan data",
      "Color Shown: Core Black/Core Black/Pulse Lilac",
    ],
    care: [
      "Machine wash cold with like colors",
      "Remove insole before washing",
      "Air dry away from direct heat",
      "Do not bleach or dry clean",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 103,
  },
  {
    id: "15",
    name: "Clifton 8",
    brand: "Hoka",
    category: "Running",
    price: 139.99,
    rating: 4.6,
    image: "/images/hoka-clifton.png",
    images: [
      "/images/hoka-clifton.png",
      "/images/hoka-clifton.png",
      "/images/hoka-clifton.png",
      "/images/hoka-clifton.png",
    ],
    isNew: false,
    releaseDate: "2022-06-01",
    description: "Lightweight, cushioned running shoe with balanced Meta-Rocker geometry.",
    fullDescription:
      "The Hoka Clifton 8 delivers the perfect combination of soft and light. Featuring an engineered mesh upper that provides breathability and targeted support. The compression-molded EVA midsole offers signature Hoka cushioning, while the early-stage Meta-Rocker geometry promotes a smooth ride. The extended heel crash pad provides a smooth transition from heel to toe.",
    details: [
      "Engineered mesh upper for breathability and support",
      "Compression-molded EVA midsole for cushioning",
      "Early-stage Meta-Rocker geometry for smooth ride",
      "Extended heel crash pad for smooth transition",
      "Lightweight design at just 8.9 oz for men's size 9",
      "Color Shown: Blue/White",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Remove insole to dry separately",
      "Avoid machine washing",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 95,
  },
  {
    id: "16",
    name: "Pegasus 39",
    brand: "Nike",
    category: "Running",
    price: 129.99,
    rating: 4.5,
    image: "/images/nike-pegasus.png",
    images: [
      "/images/nike-pegasus.png",
      "/images/nike-pegasus.png",
      "/images/nike-pegasus.png",
      "/images/nike-pegasus.png",
    ],
    isNew: false,
    releaseDate: "2022-04-28",
    description: "Versatile daily trainer with React foam and Zoom Air units for responsive cushioning.",
    fullDescription:
      "The Nike Pegasus 39 continues the legacy of the iconic running shoe with updated features for improved performance. Featuring an engineered mesh upper that provides targeted breathability and support. The React foam midsole delivers a smooth, responsive ride, while the two Zoom Air units (one more than the Pegasus 38) offer additional spring at the forefoot. The midfoot band provides a secure fit during your run.",
    details: [
      "Engineered mesh upper for breathability and support",
      "React foam midsole for smooth, responsive ride",
      "Two Zoom Air units for additional spring",
      "Midfoot band for secure fit",
      "Waffle-inspired outsole pattern for traction",
      "Color Shown: Bright Crimson/Dark Smoke Grey",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Remove insole to dry separately",
      "Avoid machine washing",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 118,
  },
  {
    id: "17",
    name: "LeBron 20",
    brand: "Nike",
    category: "Basketball",
    price: 199.99,
    rating: 4.8,
    image: "/images/nike-lebron.png",
    images: [
      "/images/nike-lebron.png",
      "/images/nike-lebron.png",
      "/images/nike-lebron.png",
      "/images/nike-lebron.png",
    ],
    isNew: true,
    releaseDate: "2023-02-15",
    description: "Low-profile performance basketball shoe with Zoom Air units and carbon fiber shank.",
    fullDescription:
      "The Nike LeBron 20 marks the 20th signature shoe for basketball legend LeBron James. Featuring a lightweight Sphere-lined upper with synthetic overlays for support and containment. The forefoot and heel Zoom Air units provide responsive cushioning, while the carbon fiber midfoot shank adds torsional rigidity. The multidirectional outsole pattern delivers excellent traction on the court.",
    details: [
      "Sphere-lined upper with synthetic overlays",
      "Forefoot and heel Zoom Air units for responsive cushioning",
      "Carbon fiber midfoot shank for torsional rigidity",
      "Multidirectional outsole pattern for traction",
      "Padded collar for comfort and support",
      "Color Shown: University Red/Metallic Gold",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Use soft brush to remove court dust from outsole",
      "Avoid wearing outdoors",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
      "US 14",
    ],
    reviews: 76,
  },
  {
    id: "18",
    name: "Jordan 36",
    brand: "Nike",
    category: "Basketball",
    price: 184.99,
    rating: 4.7,
    image: "/images/jordan-36.png",
    images: ["/images/jordan-36.png", "/images/jordan-36.png", "/images/jordan-36.png", "/images/jordan-36.png"],
    isNew: false,
    releaseDate: "2022-09-04",
    description: "Lightweight performance basketball shoe with Zoom Air strobel and leno-weave upper.",
    fullDescription:
      "The Air Jordan 36 is designed for the next generation of basketball players. Featuring a lightweight leno-weave upper that provides containment and breathability. The full-length Zoom Air strobel unit is stitched directly to the upper, sitting closer to your foot for responsive cushioning. The carbon fiber midfoot shank provides torsional rigidity, while the multidirectional outsole pattern delivers excellent traction on the court.",
    details: [
      "Leno-weave upper for containment and breathability",
      "Full-length Zoom Air strobel unit for responsive cushioning",
      "Carbon fiber midfoot shank for torsional rigidity",
      "Multidirectional outsole pattern for traction",
      "Padded collar for comfort and support",
      "Color Shown: Black/Infrared 23/White",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Use soft brush to remove court dust from outsole",
      "Avoid wearing outdoors",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 82,
  },
  {
    id: "19",
    name: "Harden Vol. 6",
    brand: "Adidas",
    category: "Basketball",
    price: 149.99,
    rating: 4.5,
    image: "/images/adidas-harden.png",
    images: [
      "/images/adidas-harden.png",
      "/images/adidas-harden.png",
      "/images/adidas-harden.png",
      "/images/adidas-harden.png",
    ],
    isNew: false,
    releaseDate: "2022-07-20",
    description: "Signature basketball shoe with Boost cushioning and supportive lacing system.",
    fullDescription:
      "The Adidas Harden Vol. 6 is designed for James Harden's dynamic playing style. Featuring a textile upper with synthetic overlays for lightweight support and durability. The Boost cushioning provides responsive comfort, while the supportive lacing system offers a secure fit. The rubber outsole with multidirectional traction pattern is designed for quick cuts and explosive movements on the court.",
    details: [
      "Textile upper with synthetic overlays",
      "Boost cushioning for responsive comfort",
      "Supportive lacing system for secure fit",
      "Rubber outsole with multidirectional traction pattern",
      "Padded collar for comfort and support",
      "Color Shown: Core Black/Team Solar Green",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Use soft brush to remove court dust from outsole",
      "Avoid wearing outdoors",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 68,
  },
  {
    id: "20",
    name: "Curry 9",
    brand: "Under Armour",
    category: "Basketball",
    price: 159.99,
    rating: 4.6,
    image: "/images/under-armour-curry.png",
    images: [
      "/images/under-armour-curry.png",
      "/images/under-armour-curry.png",
      "/images/under-armour-curry.png",
      "/images/under-armour-curry.png",
    ],
    isNew: false,
    releaseDate: "2022-05-12",
    description: "Lightweight basketball shoe with UA Flow cushioning and supportive upper.",
    fullDescription:
      "The Under Armour Curry 9 is designed for Stephen Curry's quick, agile playing style. Featuring a lightweight, breathable upper with strategic support zones for lateral stability. The UA Flow cushioning eliminates the rubber outsole, reducing weight and providing a more direct connection to the court. The internal fit system ensures a secure, comfortable fit during quick cuts and explosive movements.",
    details: [
      "Lightweight, breathable upper with support zones",
      "UA Flow cushioning for court feel and traction",
      "Internal fit system for secure, comfortable fit",
      "Durable toe wrap for added protection",
      "Padded collar for comfort and support",
      "Color Shown: Blue/White/Yellow",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Air dry away from direct heat",
      "Use soft brush to remove court dust from outsole",
      "Avoid wearing outdoors",
      "Store in a cool, dry place",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 74,
  },
  {
    id: "21",
    name: "SB Dunk Low Pro",
    brand: "Nike",
    category: "Limited Edition",
    price: 129.99,
    rating: 4.8,
    image: "/images/nike-sb-dunk.png",
    images: [
      "/images/nike-sb-dunk.png",
      "/images/nike-sb-dunk.png",
      "/images/nike-sb-dunk.png",
      "/images/nike-sb-dunk.png",
    ],
    isNew: true,
    releaseDate: "2023-01-28",
    description: "Skate-ready version of the iconic Dunk with Zoom Air cushioning and padded tongue.",
    fullDescription:
      "The Nike SB Dunk Low Pro takes the iconic basketball silhouette and optimizes it for skateboarding. Featuring a leather and suede upper for durability and style. The Zoom Air unit in the heel provides responsive cushioning, while the padded tongue and collar offer comfort and protection. The rubber outsole with modified traction pattern is designed specifically for grip and board feel.",
    details: [
      "Leather and suede upper for durability and style",
      "Zoom Air unit in heel for responsive cushioning",
      "Padded tongue and collar for comfort and protection",
      "Rubber outsole with modified traction pattern",
      "Perforated toe box for breathability",
      "Color Shown: Summit White/Black/University Red",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Use soft brush for suede sections",
      "Air dry away from direct heat",
      "Apply suede protector spray",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 92,
  },
  {
    id: "22",
    name: "Travis Scott x Air Jordan 1",
    brand: "Nike",
    category: "Limited Edition",
    price: 349.99,
    rating: 4.9,
    image: "/images/nike-travis-scott.png",
    images: [
      "/images/nike-travis-scott.png",
      "/images/nike-travis-scott.png",
      "/images/nike-travis-scott.png",
      "/images/nike-travis-scott.png",
    ],
    isNew: false,
    releaseDate: "2022-11-10",
    description: "Highly coveted collaboration featuring reversed Swoosh and premium materials.",
    fullDescription:
      "The Travis Scott x Air Jordan 1 is one of the most coveted collaborations in sneaker culture. Featuring a premium suede and leather upper with the signature reversed Swoosh on the lateral side. The hidden stash pocket inside the collar adds a unique functional element, while the Cactus Jack branding on the tongue and heel provides distinctive style. The Air-Sole unit in the heel delivers classic cushioning.",
    details: [
      "Premium suede and leather upper",
      "Reversed Swoosh on lateral side",
      "Hidden stash pocket inside collar",
      "Cactus Jack branding on tongue and heel",
      "Air-Sole unit in heel for cushioning",
      "Color Shown: Mocha/Black/University Red",
    ],
    care: [
      "Spot clean with mild soap and water",
      "Use soft brush for suede sections",
      "Air dry away from direct heat",
      "Apply suede protector spray",
      "Store in a cool, dry place",
    ],
    sizes: ["US 7", "US 7.5", "US 8", "US 8.5", "US 9", "US 9.5", "US 10", "US 10.5", "US 11", "US 11.5", "US 12"],
    reviews: 156,
  },
  {
    id: "23",
    name: "Yeezy 700 V3",
    brand: "Adidas",
    category: "Limited Edition",
    price: 299.99,
    rating: 4.7,
    image: "/images/adidas-yeezy-700.png",
    images: [
      "/images/adidas-yeezy-700.png",
      "/images/adidas-yeezy-700.png",
      "/images/adidas-yeezy-700.png",
      "/images/adidas-yeezy-700.png",
    ],
    isNew: false,
    releaseDate: "2022-08-25",
    description: "Futuristic design with glow-in-the-dark cage and EVA foam cushioning.",
    fullDescription:
      "The Adidas Yeezy 700 V3 represents the evolution of Kanye West's vision for the future of footwear. Featuring a monofilament engineered mesh upper with RPU overlays for structure and durability. The PU encapsulated EVA midsole provides lightweight cushioning, while the glow-in-the-dark cage adds a distinctive futuristic aesthetic. The rubber outsole offers durable traction for everyday wear.",
    details: [
      "Monofilament engineered mesh upper with RPU overlays",
      "PU encapsulated EVA midsole for lightweight cushioning",
      "Glow-in-the-dark cage for distinctive aesthetic",
      "Rubber outsole for durable traction",
      "Reflective details for visibility in low light",
      "Color Shown: Azael/Azael/Azael",
    ],
    care: [
      "Spot clean with mild detergent and water",
      "Use soft brush for mesh upper",
      "Air dry at room temperature",
      "Use specialized sneaker cleaner for tough stains",
      "Store away from direct sunlight",
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "US 12", "US 13"],
    reviews: 88,
  },
  {
    id: "24",
    name: "Jordan 1 Chicago",
    brand: "Nike",
    category: "Limited Edition",
    price: 179.99,
    rating: 4.9,
    image: "/images/jordan-1-chicago.png",
    images: [
      "/images/jordan-1-chicago.png",
      "/images/jordan-1-chicago.png",
      "/images/jordan-1-chicago.png",
      "/images/jordan-1-chicago.png",
    ],
    isNew: true,
    releaseDate: "2023-05-01",
    description: "Iconic colorway of the legendary Air Jordan 1 silhouette.",
    fullDescription:
      "The Air Jordan 1 Chicago is perhaps the most iconic colorway of the legendary silhouette that started it all. Featuring a premium leather upper in the classic Chicago Bulls colors of white, black, and varsity red. The Air-Sole unit in the heel provides lightweight cushioning, while the padded collar offers comfort and support. The rubber outsole with pivot point delivers traction and durability for everyday wear.",
    details: [
      "Premium leather upper in Chicago Bulls colors",
      "Air-Sole unit in heel for lightweight cushioning",
      "Padded collar for comfort and support",
      "Rubber outsole with pivot point for traction",
      "Perforated toe box for breathability",
      "Color Shown: White/Black/Varsity Red",
    ],
    care: [
      "Wipe clean with a damp cloth",
      "Use leather conditioner to maintain suppleness",
      "Clean white midsoles with mild soap and water",
      "Allow to air dry naturally",
      "Use shoe trees to maintain shape",
    ],
    sizes: [
      "US 7",
      "US 7.5",
      "US 8",
      "US 8.5",
      "US 9",
      "US 9.5",
      "US 10",
      "US 10.5",
      "US 11",
      "US 11.5",
      "US 12",
      "US 13",
    ],
    reviews: 203,
  },
]

export const getProductsByCategory = (category: string) => {
  return products.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}

export const getRelatedProducts = (productId: string, limit = 4) => {
  const currentProduct = products.find((p) => p.id === productId)
  if (!currentProduct) return []

  return products
    .filter((p) => p.id !== productId && p.category === currentProduct.category)
    .sort(() => 0.5 - Math.random())
    .slice(0, limit)
}

export const getFeaturedProducts = (limit = 4): Product[] => {
  return products
    .filter(product => product.rating >= 4.7 || product.isNew)
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
}

export const getNewArrivals = (limit = 4) => {
  return products
    .filter((p) => p.isNew)
    .sort((a, b) => new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime())
    .slice(0, limit)
}

export const getProductById = (id: string): Product | undefined => {
  return products.find(product => product.id === id);
}

export const categories = [
  {
    id: "1",
    name: "Running",
    slug: "running",
    image: "/images/category-running.png",
    description: "Engineered for speed, comfort, and endurance on any terrain.",
  },
  {
    id: "2",
    name: "Lifestyle",
    slug: "lifestyle",
    image: "/images/category-lifestyle.png",
    description: "Everyday comfort with street-ready style for any occasion.",
  },
  {
    id: "3",
    name: "Basketball",
    slug: "basketball",
    image: "/images/category-basketball.png",
    description: "Performance-driven designs for explosive moves on the court.",
  },
  {
    id: "4",
    name: "Limited Edition",
    slug: "limited-edition",
    image: "/images/category-limited.png",
    description: "Exclusive collaborations and rare releases for collectors and enthusiasts.",
  },
]

export const getCategoryBySlug = (slug: string) => {
  return categories.find((category) => category.slug === slug)
}

export const brands = [...new Set(products.map((product) => product.brand))]
